version: "3"
services:
  app:
    image: ashton314/program_builder
    ports:
      - "80:4000"
    links:
      - db
  db:
    image: postgres
    volumes:
      - program_builder_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: program_builder_prod
volumes:
  program_builder_volume: {}
